djangoGF/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static, serve
from django.conf import settings
import users
from GuideForum import views

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('', views.index, name='homepage'),
                  path('topics/', views.topics, name='topics'),
                  path('my_topics/', views.my_topics, name='my_topics'),
                  path('user/<int:user_id>/', views.user_profile, name='user_profile'),
                  path('topic/<int:topic_id>/', views.topic, name='topic'),
                  path('topic/<int:topic_id>/like/', views.like_topic, name='like_topic'),
                  path('topic/<int:topic_id>/edit/', views.edit_topic, name='edit_topic'),
                  path('topic/<int:topic_id>/delete/', views.delete_topic, name='delete_topic'),
                  path("select2/", include("django_select2.urls")),
                  path('new_topic/', views.new_topic, name='new_topic'),
                  path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
                  path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, view=serve)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', views.register, name='register'),
]

GuideForum/forms.py
from django import forms
from django_select2.forms import Select2TagWidget
from . import models


class TopicForm(forms.ModelForm):
    tags = forms.CharField(
        widget=Select2TagWidget(attrs={
            'data-placeholder': 'Choose tags',
            'data-tags': 'true',
            'data-token-separators': "[',', ' ']",
        }),
        required=False,
    )

    preview = forms.ImageField(widget=forms.ClearableFileInput, required=False)

    class Meta:
        model = models.Topic
        fields = ['title', 'description', 'tags', 'preview', 'text']
        labels = {
            'title': 'Title of your guide',
            'description': 'Short description',
            'text': 'Briefly explain your guide here'
        }

    def clean(self):
        cleaned_data = super().clean()
        clear_preview = self.cleaned_data.get('clear_preview')

        if clear_preview:
            cleaned_data['preview'] = None

        return cleaned_data


class EntryForm(forms.ModelForm):
    class Meta:
        model = models.Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Guide Forum</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'homepage' %}">Homepage</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'topics' %}">All topics</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'my_topics' %}">My topics</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_profile' user.id %}">Hello, {{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
{% block content %} {% endblock content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/select2.js' %}"></script>
</body>
</html>

templates/edit_entry.html
{% extends 'base.html' %}
{% block content %}
    <p>
    <a href="{% url 'topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>Edit entry:</p>
    <form action="{% url 'edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
    </form>
{% endblock content %}

templates/edit_topic.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <style>
        #id_tags {
            width: 100%;
        }

        .select2-container--default .select2-selection--multiple {
            width: 100%;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            display: inline-block;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    <p>Edit topic:</p>
    <form action="{% url 'edit_topic' topic_id=topic.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title }}
            {% for error in form.title.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            {{ form.description }}
            {% for error in form.description.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_tags">Tags:</label>
            <select name="tags" id="id_tags" multiple> <!-- HERE -->
                {% for tag in topic.tags.all %}
                    <option selected>{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_preview">Preview:</label>
            <input type="file" name="preview" id="id_preview">
        </div>
        <div class="form-group">
            {{ form.text.label_tag }}
            {{ form.text }}
            {% for error in form.text.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
    <script>
        $(document).ready(function () {
            $('#id_tags').select2({
                tags: true,
                width: '20%'
            });
        });
    </script>
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block content %}
    <p>Body here</p>
{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<div class="wrapper">
    <div class="title">
        Login Form
    </div>
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        <div class="field">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="field">
            {{ form.password.label_tag }}
            {{ form.password }}
        </div>
        <div class="field">
            <input type="submit" value="Login">
        </div>
        <div class="signup-link">
            Not a member? <a href="{% url 'users:register' %}">Signup now</a>
        </div>
    </form>
</div>
</body>
</html>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<div class="wrapper">
    <div class="title">
        Logged out <br>
        <a href="{% url 'homepage' %}">Back to Homepage</a>
    </div>
</div>
</body>
</html>

templates/new_entry.html
{% extends "base.html" %}
{% block content %}
    <p>
        <a href="{% url 'topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>Add a new entry</p>
    <form action="{% url 'new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

templates/new_topic.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <style>
        #id_tags {
            width: 100%;
        }

        .select2-container--default .select2-selection--multiple {
            width: 100%;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            display: inline-block;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    <p>Add a new topic:</p>
    <form action="{% url 'new_topic' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title }}
            {% for error in form.title.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            {{ form.description }}
            {% for error in form.description.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.tags.label_tag }}
            {{ form.tags }}
            {% for error in form.tags.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.preview.label_tag }}
            {{ form.preview }}
            {% for error in form.preview.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.text.label_tag }}
            {{ form.text }}
            {% for error in form.text.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Add topic</button>
    </form>
    <script>
        $(document).ready(function () {
            $('#id_tags').select2({
                tags: true,
                width: '20%'
            });
        });
    </script>
{% endblock content %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
   <div class="wrapper">
      <div class="title">
         Register Form
      </div>
      <form method="post" action="{% url 'users:register' %}">
         {% csrf_token %}
         <div class="field">
            {{ form.username.label_tag }}
            {{ form.username }}
         </div>
         <div class="field">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
         </div>
         <div class="field">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
         </div>
         <div class="field">
            <input type="submit" name="submit" value="Register">
         </div>
         <div class="signup-link">
            Already a member? <a href="{% url 'users:login' %}">Login now</a>
         </div>
      </form>
   </div>
</body>
</html>

templates/topic.html
{% extends 'base.html' %}
{% block content %}
    {% load mathfilters %}
    <p>Topic: {{ topic }}</p>
    <p>Description: {{ topic.description }}</p>
    <p>Read time: {{ topic.text|length|add:999|div:1000|floatformat:0 }} min read</p>
    <img src="{{ topic.preview.url }}">
    <p>Owner:
        {% if topic.owner %}
            <a href="{% url 'user_profile' topic.owner.id %}">
                {{ topic.owner }}
            </a>
        {% else %}
            Unknown
        {% endif %}
    </p>
    <p>Date_added: {{ topic.date_added }}</p>
    <p>Tags:</p>
    <ul>
        {% for tag in topic.tags.all %}
            <li>
                <p>{{ tag.name }}</p>
            </li>
        {% endfor %}
    </ul>
    <p>{{ topic.text }}</p>
    <p>{{ topic.rating }}</p>
    <form action="{% url 'like_topic' topic.id %}" method="POST">
        {% csrf_token %}
        {% if request.user in topic.likes.all %}
            <button type="submit" class="btn btn-primary">Liked</button>
        {% else %}
            <button type="submit" class="btn btn-primary">Like</button>
        {% endif %}
    </form>
    {% if can_edit %}
        {% if topic.id %}
            <a href="{% url 'edit_topic' topic_id=topic.id %}">Edit Topic</a>
        {% endif %}
        <form method="post" action="{% url 'delete_topic' topic.id %}"
              onsubmit="return confirm('Are you sure you want to delete this topic?');">
            {% csrf_token %}
            <input type="submit" value="Delete Topic">
        </form>
    {% endif %}
    <p>Entries:</p>
    <p>
        <a href="{% url 'new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'edit_entry' entry.id %}">edit entry</a>
                </p>
            </li>
        {% empty %}
            <li>
                There are no entries for this topic yet
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/topics.html
{% extends "base.html" %}
{% block content %}
    <style>
        /* Add this CSS to your custom CSS file */

        /* Reduce left and right margins of the container */
        .container {
            margin-left: auto;
            margin-right: auto;
            max-width: 100%;
        }

        /* Adjust the width of the filter column */
        .col-md-2 {
            flex: 0 0 20%;
            max-width: 20%;
        }

        /* Adjust the width of the topic display column */
        .col-md-8 {
            flex: 0 0 60%;
            max-width: 60%;
        }

        /* Reduce the width of the topic cards */
        .card {
            width: 100%;
        }

        /* Adjust the size of the topic preview image */
        .topic-preview {
            width: 100%;
            height: auto;
        }

        /* Center the topic preview image within the card */
        .card-body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        /* Adjust the width of the "Add a new topic" column */
        .col-md-2:last-child {
            flex: 0 0 20%;
            max-width: 20%;
        }

        .topic-preview {
            width: 100%;
            height: auto;
        }

        /* Adjust the position of the "Add a new topic" button */
        .add-topic-button {
            margin-left: auto;
            margin-right: 20px;
        }

    </style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>Topics</h1>
                <form class="mb-3 d-flex" method="GET" action="{% url 'topics' %}">
                    <div class="form-group flex-grow-1 mr-2">
                        <label for="search-input"></label>
                        <input type="text" id="search-input" name="q" class="form-control form-control-lg"
                               placeholder="Search topics"
                               value="{{ query }}">
                    </div>
                    <button type="submit" class="btn btn-outline-primary btn-lg">Search</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 bg-light">
                <div class="p-3">
                    <!-- Tag Filter Buttons -->
                    <h3>Filter by tags:</h3>
                    {% for tag in tags %}
                        {% if tag.id in selected_tags %}
                            <a href="{% url 'topics' %}?q={{ query }}{% for selected_tag in selected_tags %}{% if selected_tag != tag.id %}&tag={{ selected_tag }}{% endif %}{% endfor %}"
                               class="btn btn-primary tag-button selected">{{ tag.name }} (selected)</a>
                        {% else %}
                            <a href="{% url 'topics' %}?q={{ query }}{% for selected_tag in selected_tags %}&tag={{ selected_tag }}{% endfor %}&tag={{ tag.id }}"
                               class="btn btn-outline-primary tag-button">{{ tag.name }}</a>
                        {% endif %}
                    {% empty %}
                        <p>No tags found</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-8">
                <div class="container">
                    <div class="row">
                        {% for topic in topics %}
                            <div class="col-md-4">
                                <div class="card mb-4 shadow-sm">
                                    <img class="topic-preview" src="{{ topic.preview.url }}" alt="Topic preview">
                                    <div class="card-body">
                                        {% if topic.description %}
                                            <p class="card-text">{{ topic.description }}</p>
                                        {% else %}
                                            <p class="card-text">{{ topic }}</p>
                                        {% endif %}
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group">
                                                <a href="{% url 'topic' topic.id %}" class="btn btn-sm btn-outline-primary">View</a>
                                                <a href="{% url 'user_profile' topic.owner_id %}" class="btn btn-sm btn-outline-secondary">See {{ topic.owner.user.username }}</a>
                                            </div>
                                        </div>
                                        <div>
                                            <small class="text-primary">{{ topic.rating }}</small>
                                        </div>
                                        <div class="text-muted">
                                            <small class="text-muted">{{ topic.date_added|date:'M d, Y H:i' }}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <li>No topics have been added yet</li>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-2 bg-light">
                <div class="p-3">
                    <a href="{% url 'new_topic' %}" class="btn btn-outline-primary add-topic-button">Add a new topic</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user_profile.html
{% extends 'base.html' %}
{% block content %}
    <p>Страница пользователя {{ user_profile.user.username }}</p>
    <p>Bio: {{ user_profile.user_description }}</p>
    <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
    {% if request.user == user_profile.user %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="profile_picture">
            <input type="submit" value="Загрузить">
        </form>
        <form method="post">
            {% csrf_token %}
            <textarea name="user_description">{{ user_profile.user_description }}</textarea>
            <input type="submit" value="Изменить информацию о себе">
        </form>
    {% endif %}
    <p>Гайды:</p>
    {% for topic in topics %}
        <a href="{% url 'topic' topic.id %}">{{ topic.title }}</a>
    {% empty %}
        <p>No topics found.</p>
    {% endfor %}
{% endblock content %}